--EGM Services
SELECT FK_PATIENT_ID 
	, ACTIVITY_TYPE_CD 
	, FACILITY_REVENUE_CENTER_CD 
	, FK_PROCEDURE_ID 
	, PROCEDURE_HCPCS_CD 
	, PROCEDURE_HCPCS_MOD_CD_LIST 
	, PROCEDURE_HCPCS_MOD_CD_LIST[0] AS mod0
	, PROCEDURE_HCPCS_MOD_CD_LIST[1] AS mod1
	, PROCEDURE_HCPCS_MOD_CD_LIST[2] AS mod2
	, PROCEDURE_ICD_9_CD 
	, PROCEDURE_ICD_10_CD 
	, MEDICATION_NDC_SPL_CD	
	, MEDICATION_HCPCS_CD
	, DME_HCPCS_CD
	, CASE 
		WHEN claim_type_cd = '40' THEN 'op'
		WHEN claim_type_cd IN ('70','71') THEN 'pb'
		WHEN claim_type_cd IN ('60', '61') THEN 'ip'
		WHEN claim_type_cd = '10' THEN 'hh'
		-- other cases
	  END AS src_file	
	, CASE 
		WHEN ACTIVITY_TYPE_CD = 'fac_proc'
			THEN coalesce(NULLIF(PROCEDURE_ICD_9_CD,'#NA'), NULLIF(PROCEDURE_ICD_9_CD,'#NA'))
		WHEN ACTIVITY_TYPE_CD = 'med'
			THEN MEDICATION_NDC_SPL_CD	--is MEDICATION_HCPCS_CD useful? is it used in Services?
		WHEN ACTIVITY_TYPE_CD = 'dme'	
			THEN DME_HCPCS_CD
		ELSE PROCEDURE_HCPCS_CD 			
	  END AS src_code
FROM insights.ACTIVITY 